filebeat.inputs:
- type: log
  enabled: true
{% if logtype == "json" %}
  json.keys_under_root: true
{% endif %}
  paths:
    - {{loglocation}}
  fields:
   component: {{COMPONENT}} 
   logtype: {{logtype}}

output.logstash:
  hosts: ["172.31.85.10:5044"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~



