- name: Copy the prometheus config 
  ansible.builtin.template:
    src: prometheus.yml 
    dest: /opt/prometheus/prometheus.yml 

- name: Restart logstash 
  systemd:
    name: prometheus 
    state: restarted 

# I want to consider the restart as success only when the port 5044 is opened 
- name: Waits for prometheus port 9090 to open 
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    connect_timeout: 10