- name: Configure Yum Repos 
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - nodejs
      - gcc-c++ 
    state: present 

- name: App user {{APPUSER}} User Creation
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user 

- name: Download DocDB Pem File 
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/
    mode: '0440'
    owner: roboshop 
    group: roboshop 

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/


- name: Configuring and Starting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: systemd 

# Installs Filebeat
- name: Configure Filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
  when: cart

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname