APPUSER: roboshop
GITHUB_REPO_URL: "https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip"
NEXUS_URL: "http://172.31.8.134:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{TAG_NAME}}.zip"
SECRETS: "{{ lookup('amazon.aws.aws_secret', 'roboshop/secrets/all', region='us-east-1') }}"